## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
  allow_failures:
  - julia: nightly
  include:
      - os: osx
        julia: 1.0

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - docs/make.jl
  after_success: skip
